services:
  postgres:
    image: postgres:16-alpine
    container_name: user-ms-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: user_ms
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U usr -d user_ms"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
