spring.application.name=order-ms
server.servlet.context-path=/order-ms
server.port=8004
spring.autoconfigure.exclude=org.springframework.boot.security.autoconfigure.UserDetailsServiceAutoConfiguration
jwt.secret=${JWT_SECRET:QWluZGEgcXVlIGV1IGFuZGFzc2UgcGVsbyB2YWxlIGRhIHNvbWJyYSBkYSBtb3J0ZSwgbsOjbyB0ZW1lcmlhIG1hbCBhbGd1bSwgcG9ycXVlIHR1IGVzdMOhcyBjb21pZ287IGEgdHVhIHZhcmEgZSBvIHRldSBjYWphZG8gbWUgY29uc29sYW0uU2FsbW9zIDIzOjQ=}

spring.datasource.url=jdbc:postgresql://localhost:5435/order_ms
spring.datasource.username=usr
spring.datasource.password=pwd
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.enabled=true

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=usr
spring.rabbitmq.password=pwd
app.messaging.user-created-queue=order-ms-user-created-queue
app.messaging.user-deleted-queue=order-ms-user-deleted-queue
app.messaging.order-created-queue=order-created
app.messaging.payment-approved-queue=payment-approved
app.messaging.payment-failed-queue=payment-failed

catalog.base-url=${CATALOG_MS_BASE_URL:http://localhost:8003/catalog-ms}
