spring.application.name=user-ms
server.servlet.context-path=/user-ms
server.port=8001
spring.autoconfigure.exclude=org.springframework.boot.security.autoconfigure.UserDetailsServiceAutoConfiguration
jwt.secret=${JWT_SECRET:QWluZGEgcXVlIGV1IGFuZGFzc2UgcGVsbyB2YWxlIGRhIHNvbWJyYSBkYSBtb3J0ZSwgbsOjbyB0ZW1lcmlhIG1hbCBhbGd1bSwgcG9ycXVlIHR1IGVzdMOhcyBjb21pZ287IGEgdHVhIHZhcmEgZSBvIHRldSBjYWphZG8gbWUgY29uc29sYW0uU2FsbW9zIDIzOjQ=}
jwt.expiration=86400000

spring.datasource.url=jdbc:postgresql://localhost:5432/user_ms
spring.datasource.username=usr
spring.datasource.password=pwd
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=usr
spring.rabbitmq.password=pwd
app.messaging.user-created-exchange=user.created
app.messaging.user-deleted-exchange=user.deleted